FROM clamav/clamav:stable
USER root
RUN apk add --no-cache python3 py3-pip && python3 -m venv /opt/scanner-venv && /opt/scanner-venv/bin/pip install --no-cache-dir Flask gunicorn
COPY malware_scanner.py /opt/malibub/malware_scanner.py
COPY scanner-start.sh /opt/malibub/scanner-start.sh
RUN chmod +x /opt/malibub/scanner-start.sh
EXPOSE 10000
CMD ["/opt/malibub/scanner-start.sh"]
